import { StyleSheet } from 'react-native';
import { Colors } from '../theme/colors';
import { Fonts } from '../theme/fonts';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fff' },
  container: { flex: 1, backgroundColor: '#F5F5F5' },
  scrollContent: { paddingBottom: 40 },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
  },

  // Header
  header: {
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingBottom: 28,
    paddingTop: 8,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  editButton: {
    alignSelf: 'flex-end',
    marginRight: 16,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.orange,
  },
  editButtonText: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 13,
    color: Colors.orange,
  },
  avatarRing: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 2,
    borderColor: Colors.orange,
    padding: 2,
    marginBottom: 16,
  },
  avatar: { width: '100%', height: '100%', borderRadius: 44 },
  avatarPlaceholder: {
    backgroundColor: Colors.orange,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontFamily: Fonts.gothamBold, fontSize: 36, color: '#fff' },
  displayName: {
    fontFamily: Fonts.gothamBold,
    fontSize: 22,
    color: Colors.blueGrey,
    marginBottom: 4,
  },
  emailText: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 14,
    color: '#687076',
  },
  userTypeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 8,
  },
  userTypeBadgeText: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 11,
    textTransform: 'uppercase',
  },
  badgeDefault: {
    backgroundColor: Colors.orange + '20',
    borderWidth: 1,
    borderColor: Colors.orange,
  },
  badgeSecondary: {
    backgroundColor: '#F1F3F5',
    borderWidth: 1,
    borderColor: '#D7DBDF',
  },
  badgeTextDefault: {
    color: Colors.orange,
  },
  badgeTextSecondary: {
    color: '#687076',
  },

  // Stats
  statsRow: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  statCard: { flex: 1, alignItems: 'center' },
  statValue: {
    fontFamily: Fonts.gothamBold,
    fontSize: 24,
    color: Colors.blueGrey,
    marginBottom: 4,
  },
  statLabel: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 12,
    color: '#687076',
  },
  statDivider: { width: 1, backgroundColor: '#E8E8E8' },

  // Region + Member Since meta card
  metaCard: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginTop: 12,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  metaRow: { flexDirection: 'row', alignItems: 'center' },
  metaIcon: { marginRight: 8 },
  metaLabel: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 13,
    color: '#687076',
    flex: 1,
  },
  metaValue: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 13,
    color: Colors.blueGrey,
  },

  // Key Wallet
  keyWallet: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  keyWalletLeft: { flex: 1 },
  keyWalletTitle: {
    fontFamily: Fonts.gothamBold,
    fontSize: 15,
    color: Colors.blueGrey,
    marginBottom: 2,
  },
  keyWalletSub: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 12,
    color: '#687076',
  },
  keyWalletRight: { alignItems: 'center', gap: 8 },
  keyCountWrap: {
    alignItems: 'center',
    backgroundColor: Colors.orange + '18',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 12,
  },
  keyCount: { fontFamily: Fonts.gothamBold, fontSize: 28, color: Colors.orange },
  keyUnit: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 12,
    color: Colors.orange,
  },
  buyKeysBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.orange,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
  },
  buyKeysBtnText: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 12,
    color: '#fff',
  },

  // Menu
  sectionLabel: {
    fontFamily: Fonts.gothamBold,
    fontSize: 12,
    color: '#687076',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginHorizontal: 24,
    marginTop: 24,
    marginBottom: 8,
  },
  menuCard: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  signOutCard: { marginTop: 24 },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  menuRowLeft: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  menuIcon: { marginRight: 12 },
  menuLabel: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 15,
    color: Colors.blueGrey,
  },
  destructiveText: { color: Colors.error },
  rowDivider: { height: 1, backgroundColor: '#F0F0F0', marginLeft: 48 },

  // ---------------------------------------------------------------------------
  // BuyKeysModal styles
  // ---------------------------------------------------------------------------
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 36,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  modalTitle: {
    fontFamily: Fonts.gothamBold,
    fontSize: 18,
    color: Colors.blueGrey,
  },
  modalSubtitle: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 13,
    color: '#687076',
    marginBottom: 16,
  },
  modalCentered: { alignItems: 'center', paddingVertical: 32 },
  noPackagesText: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 14,
    color: '#9AA0A6',
    textAlign: 'center',
  },

  // Package card
  packageCard: {
    borderWidth: 1,
    borderColor: '#E9ECEF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  packageCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  packageName: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 15,
    color: Colors.blueGrey,
    flex: 1,
  },
  packagePriceWrap: { alignItems: 'flex-end' },
  packagePrice: {
    fontFamily: Fonts.gothamBold,
    fontSize: 16,
    color: Colors.blueGrey,
  },
  packagePriceStrike: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 13,
    color: '#9AA0A6',
    textDecorationLine: 'line-through',
  },
  packagePriceDiscount: {
    fontFamily: Fonts.gothamBold,
    fontSize: 16,
    color: '#16A34A',
  },
  packageDesc: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 13,
    color: '#687076',
    marginBottom: 8,
  },
  packageKeysRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 12,
  },
  packageKeys: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 13,
    color: Colors.orange,
  },
  packageSelectBtn: {
    backgroundColor: Colors.orange,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  packageSelectText: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 14,
    color: '#fff',
  },

  // Confirm step
  confirmDesc: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 14,
    color: '#374151',
    lineHeight: 22,
    marginBottom: 20,
  },
  originalPriceStrike: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 14,
    color: '#9AA0A6',
    textDecorationLine: 'line-through',
  },
  promoPriceHighlight: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 16,
    color: '#DC2626',
  },

  // Promo code
  promoWrap: { marginBottom: 20 },
  promoLabel: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 13,
    color: Colors.blueGrey,
    marginBottom: 8,
  },
  promoRow: { flexDirection: 'row', gap: 8 },
  promoInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontFamily: Fonts.firaSansRegular,
    fontSize: 14,
    color: Colors.blueGrey,
  },
  promoApplyBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.orange,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 70,
  },
  promoApplyText: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 13,
    color: Colors.orange,
  },
  promoError: {
    fontFamily: Fonts.firaSansRegular,
    fontSize: 12,
    color: '#EF4444',
    marginTop: 6,
  },
  promoSuccess: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 12,
    color: '#16A34A',
    marginTop: 6,
  },

  // Confirm footer
  confirmFooter: { flexDirection: 'row', gap: 12, marginTop: 8 },
  backBtn: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    alignItems: 'center',
  },
  backBtnText: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 14,
    color: Colors.blueGrey,
  },
  confirmBtn: {
    flex: 2,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#16A34A',
    alignItems: 'center',
  },
  confirmBtnText: { fontFamily: Fonts.firaSansBold, fontSize: 14, color: '#fff' },

  // Modal cancel
  modalCancelBtn: {
    marginTop: 12,
    paddingVertical: 13,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    alignItems: 'center',
  },
  modalCancelText: {
    fontFamily: Fonts.firaSansBold,
    fontSize: 14,
    color: Colors.blueGrey,
  },
});
